### ISSUE TITLE
yarn dev does not work

### ISSUE THREAD

**Issue by norakola** [PatrickAlphaC/nextjs-ethers-metamask-connect#2]
Hello Guys,
My terminal says: command dev not found. 
The ÚI/website won't pop up, is there another possibility?
My yarn version is v1.22.21

**Comment by PatrickAlphaC** [comment]
Hmm, I don't have enough information to help out here.

Could you read this guide to help you give more information? For example, what's the exact command you ran, what's your setup, etc.

https://stackoverflow.com/help/how-to-ask

**Comment by norakola** [comment]
I forgot to install nextjs, then it worked

**Comment by norakola** [comment]
I forgot to install nextjs, then it worked
